// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddApp() {
  return window['go']['main']['App']['AddApp']();
}

export function AddPaths(arg1) {
  return window['go']['main']['App']['AddPaths'](arg1);
}

export function CaptureRunning() {
  return window['go']['main']['App']['CaptureRunning']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function LaunchAll() {
  return window['go']['main']['App']['LaunchAll']();
}

export function LaunchApp(arg1, arg2) {
  return window['go']['main']['App']['LaunchApp'](arg1, arg2);
}

export function RemoveApp(arg1, arg2) {
  return window['go']['main']['App']['RemoveApp'](arg1, arg2);
}

export function SaveConfig() {
  return window['go']['main']['App']['SaveConfig']();
}

export function SetAutoRestore(arg1) {
  return window['go']['main']['App']['SetAutoRestore'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}
