// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddApp():Promise<boolean>;

export function AddPaths(arg1:Array<string>):Promise<number>;

export function CaptureRunning():Promise<number>;

export function GetConfig():Promise<main.Config>;

export function LaunchAll():Promise<string>;

export function LaunchApp(arg1:string,arg2:number):Promise<void>;

export function RemoveApp(arg1:string,arg2:number):Promise<void>;

export function SaveConfig():Promise<void>;

export function SetAutoRestore(arg1:boolean):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;
